In [1]:
import torch.nn as nn
import torch
import numpy as np
  

/opt/conda/envs/index/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


测试nn.lineara()函数

In [2]:
X_2dim=np.array([[1,2,3,4],[2,3,45,6]]) #二维数组(2,4)
X_3dim=np.array([[[1,2,3,4],[2,3,4,6],[3,4,5,5]],[[1,1,5,6],[0,0,6,5],[3,3,5,7]]]) # 三维数组（2,3,4）
 
#转成tensor的形式，因为Linear要求输入是float类型，因此还需要转成float32
X2_tensor=torch.from_numpy(X_2dim.astype(np.float32))
X3_tensor=torch.from_numpy(X_3dim.astype(np.float32))
 
#用来改变最后数组最后一维的维度
#用来缩小或者扩展特征维度
emdeding=nn.Linear(4,3)
Y2=emdeding(X2_tensor)
Y3=emdeding(X3_tensor)
 
#输出
print(Y2)
print(Y3)
 
# #Y2
# tensor([[ 0.6468,  0.6430,  0.4253],
#         [-2.9180, -3.3393,  6.3075]], grad_fn=<AddmmBackward>)
 
# #Y3
# tensor([[[0.6468, 0.6430, 0.4253],
#          [1.0562, 0.8781, 0.6216],
#          [0.7615, 0.3500, 0.7439]],
 
#         [[1.1430, 0.6462, 0.8132],
#          [0.7745, 0.4598, 0.9190],
#          [1.4516, 0.5589, 0.8545]]], grad_fn=<AddBackward0>)

tensor([[ 1.4079, -2.3592, -0.1182],
        [11.4198, -2.7018,  5.5656]], grad_fn=<AddmmBackward0>)
tensor([[[ 1.4079, -2.3592, -0.1182],
         [ 1.7555, -3.3894, -0.1197],
         [ 0.9583, -2.9405,  1.0735]],

        [[ 3.0031, -3.2589, -0.8945],
         [ 3.5085, -2.6882, -1.0139],
         [ 2.0821, -3.8737,  0.0200]]], grad_fn=<AddBackward0>)


In [4]:
emdeding.weight

Parameter containing:
tensor([[-0.2908, -0.3606,  0.2357,  0.3816],
        [-0.0081, -0.0528,  0.0168, -0.4930],
        [ 0.3992,  0.2572,  0.1387, -0.3982]], requires_grad=True)

In [15]:
emdeding.bias

Parameter containing:
tensor([ 0.1862, -0.3237,  0.1451], requires_grad=True)

In [12]:
print(X_3dim[0,0,:])

[1 2 3 4]


In [16]:
wgt=emdeding.weight.detach().numpy()
bias=emdeding.bias.detach().numpy()
np.dot(wgt,X_3dim[0,0,:])+bias

array([ 1.40790838, -2.3592093 , -0.11824024])

In [6]:
# a= '{""Plan"": {""Node Type"": ""Gather"", ""Parallel Aware"": false, ""Startup Cost"": 23540.58, ""Total Cost"": 154548.95, ""Plan Rows"": 567655, ""Plan Width"": 119, ""Actual Startup Time"": 386.847, ""Actual Total Time"": 646.972, ""Actual Rows"": 283812, ""Actual Loops"": 1, ""Workers Planned"": 2, ""Workers Launched"": 2, ""Single Copy"": false, ""Plans"": [{""Node Type"": ""Hash Join"", ""Parent Relationship"": ""Outer"", ""Parallel Aware"": true, ""Join Type"": ""Inner"", ""Startup Cost"": 22540.58, ""Total Cost"": 96783.45, ""Plan Rows"": 236523, ""Plan Width"": 119, ""Actual Startup Time"": 369.985, ""Actual Total Time"": 518.487, ""Actual Rows"": 94604, ""Actual Loops"": 3, ""Inner Unique"": false, ""Hash Cond"": ""(t.id = mi_idx.movie_id)"", ""Workers"": [], ""Plans"": [{""Node Type"": ""Seq Scan"", ""Parent Relationship"": ""Outer"", ""Parallel Aware"": true, ""Relation Name"": ""title"", ""Alias"": ""t"", ""Startup Cost"": 0.0, ""Total Cost"": 49166.46, ""Plan Rows"": 649574, ""Plan Width"": 94, ""Actual Startup Time"": 0.366, ""Actual Total Time"": 147.047, ""Actual Rows"": 514421, ""Actual Loops"": 3, ""Filter"": ""(kind_id = 7)"", ""Rows Removed by Filter"": 328349, ""Workers"": []}, {""Node Type"": ""Hash"", ""Parent Relationship"": ""Inner"", ""Parallel Aware"": true, ""Startup Cost"": 15122.68, ""Total Cost"": 15122.68, ""Plan Rows"": 383592, ""Plan Width"": 25, ""Actual Startup Time"": 103.547, ""Actual Total Time"": 103.547, ""Actual Rows"": 306703, ""Actual Loops"": 3, ""Hash Buckets"": 65536, ""Original Hash Buckets"": 65536, ""Hash Batches"": 32, ""Original Hash Batches"": 32, ""Peak Memory Usage"": 1920, ""Workers"": [], ""Plans"": [{""Node Type"": ""Seq Scan"", ""Parent Relationship"": ""Outer"", ""Parallel Aware"": true, ""Relation Name"": ""movie_info_idx"", ""Alias"": ""mi_idx"", ""Startup Cost"": 0.0, ""Total Cost"": 15122.68, ""Plan Rows"": 383592, ""Plan Width"": 25, ""Actual Startup Time"": 0.28, ""Actual Total Time"": 54.382, ""Actual Rows"": 306703, ""Actual Loops"": 3, ""Filter"": ""(info_type_id > 99)"", ""Rows Removed by Filter"": 153308, ""Workers"": []}]}]}]}, ""Planning Time"": 2.382, ""Triggers"": [], ""Execution Time"": 654.241}'
# print(a.replace('""','"'))

# 将csv中的plan，转换成json文件再输出，方便看

# import json
# with open('./a.json','r') as f:
#     a=json.load(f)
# a

{'Plan': {'Node Type': 'Gather',
  'Parallel Aware': False,
  'Startup Cost': 23540.58,
  'Total Cost': 154548.95,
  'Plan Rows': 567655,
  'Plan Width': 119,
  'Actual Startup Time': 386.847,
  'Actual Total Time': 646.972,
  'Actual Rows': 283812,
  'Actual Loops': 1,
  'Workers Planned': 2,
  'Workers Launched': 2,
  'Single Copy': False,
  'Plans': [{'Node Type': 'Hash Join',
    'Parent Relationship': 'Outer',
    'Parallel Aware': True,
    'Join Type': 'Inner',
    'Startup Cost': 22540.58,
    'Total Cost': 96783.45,
    'Plan Rows': 236523,
    'Plan Width': 119,
    'Actual Startup Time': 369.985,
    'Actual Total Time': 518.487,
    'Actual Rows': 94604,
    'Actual Loops': 3,
    'Inner Unique': False,
    'Hash Cond': '(t.id = mi_idx.movie_id)',
    'Workers': [],
    'Plans': [{'Node Type': 'Seq Scan',
      'Parent Relationship': 'Outer',
      'Parallel Aware': True,
      'Relation Name': 'title',
      'Alias': 't',
      'Startup Cost': 0.0,
      'Total Cost': 4916